### PR TITLE
onPinEntered

### PR DESCRIPTION
**Pull request by strataga**
I needed a way to check each number of the pin as it was entered. In my use case, I am using react-native-stager and checking the validity of the pin and using instance.forceUpdate() to show or hide some error text.

ex:
```
onPinEntered={(pin) => {
  ...code
}
```

### CODE REVIEW

**Comment by strataga** [comment]
It would also be nice to get the same kind of event when the backspace was tapped. That is not in this pull request. I'm not sure how you'd like to handle that. Plus, it updated the pin in state: ie: pins.pop() to remove the last digit.

**Comment by b-asaf** [comment]
Hi @appjitsu,
I tried using your method 'onPinEntered', installed v1.3.0 - But it does not seem to be working (I only tested it on Android).
I tried 2 ways:

```
(B)
handleKeyPress = (pin) => {
  console.log('handle key press:', pin);
}

render() {
  return (
    <PinInput
              ref={"pin"}
              pinLength={6}
              value={'654321'}
              autoFocus={false}
              pinItemStyle={{width: 50, height: 50}}
              pinItemProps={{keyboardType:'number-pad'}}
(A)          onPinEntered={(pin) => { console.log('pinEnter:', pin); }}
Or
(B)          onPinEntered={this.handleKeyPress}
    />
)};
```

**Comment by strataga** [comment]
I don't this has been merged yet. Try my fork.

**Comment by b-asaf** [comment]
@appjitsu, Thanks. 
What I need to write in my package.json in order to use your fork?
Does it work for Android and iOS?

**Pull request merged**
